name: Server Package Release Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'packages/server/package.json'
      - 'packages/server/src/**'

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Check Server Version
        id: version-check
        run: |
          chmod +x .github/scripts/server-version-check.sh
          result=$(.github/scripts/server-version-check.sh)
          is_new_major=$(echo $result | cut -d' ' -f1)
          version=$(echo $result | cut -d' ' -f2)
          echo "is_new_major=$is_new_major" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Build and Release Server
        if: steps.version-check.outputs.is_new_major == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.LOGIN_TOKEN }}
        run: |
          chmod +x .github/scripts/server-build-release.sh
          .github/scripts/server-build-release.sh ${{ steps.version-check.outputs.version }}
